language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-frontend duyhoang5891/udagram-frontend:v1
  - docker tag udagram-api-feed duyhoang5891/udagram-api-feed:v1
  - docker tag udagram-api-user duyhoang5891/udagram-api-user:v1
  - docker tag reverseproxy duyhoang5891/reverseproxy:v1

after_success:
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push duyhoang5891/udagram-api-feed:v1
  - docker push duyhoang5891/udagram-api-user:v1
  - docker push duyhoang5891/udagram-frontend:v1
  - docker push duyhoang5891/reverseproxy:v1